ERR Value of `foo` is not an integer.
